services:
  postgres:
    image: postgres:16
    container_name: postgres_node
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: CC_Ordertracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arthur@09
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CC_Ordertracking"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  db-init:
    image: postgres:16
    container_name: postgres_init
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./init.sql:/init.sql
    command: >
      /bin/bash -c "
      echo 'Loading schema...' &&
      PGPASSWORD=Arthur@09 psql -h postgres -U postgres -d CC_Ordertracking -f /init.sql
      "

volumes:
  postgres_data:
